services:
  monitor:
    build:
      context: monitor
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      USB_DEVICE: "/dev/ttyUSB0"
      DB_HOST: home-inverter-grafana-monitor-influxdb-1
      DB_PORT: 8086
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: ups
      INVERTER_MODEL: "Axioma"
      IS_DEBUG: "False"
      LATITUDE: 49.842
      LONGITUDE: 24.0316
      AZIMUTH: 20
      DECLINATION: 70
      POWER: 1.8
      DAMPING: 0
      TZ: "Europe/Kyiv"
      SOLAR_VOLTAGE_ON: 150 # 0.96, 76 seems late
      SOLAR_VOLTAGE_OFF: 135 # 0.82 130 seems late
      SOLAR_MANAGEMENT: "True" # enable True or disable False
    depends_on:
      - influxdb
    tmpfs:
      - /var/run
  influxdb:
    # if you have non-arm-v7 architecture, use regular influxdb image
    image: arm32v7/influxdb
    restart: always
    ports:
      - "8086:8086" # expose for testing, no need in production
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: root
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
      DOCKER_INFLUXDB_INIT_RETENTION: 365d
      INFLUXDB_DB: ups
    volumes:
      - "metrics:/var/lib/influxdb"
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
    depends_on:
      - influxdb
volumes:
  metrics:
  grafana-data:

