services:
  monitor:
    build:
      context: monitor
    restart: always
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      DB_HOST: home-inverter-grafana-monitor-influxdb-1
      DB_PORT: 8086
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: ups1
      LOG_DETAIL: "2"
      USB_DEVICE: "/dev/ttyUSB0"
      INVERTER_MODEL: "Axioma"
#      INVERTER_MODEL: "GreenCell"
      SOLAR_VOLTAGE_ON: 140 # approx. 90% of field idle voltage
      SOLAR_VOLTAGE_OFF: 100 # approx. inverter min MPPT voltage
#      SOLAR_VOLTAGE_ON: 70 #70 # approx. 90% of field idle voltage
#      SOLAR_VOLTAGE_OFF: 50 #50 #55 #50 # 57 # inverter min MPPT voltage
      PRECARIOUS_CHARGING_ENABLED: "False" # use with caution, enable at your own risk
      GRID_CHARGING_ENABLED: "False"
      GRID_CHARGING_FLOAT: 26.6
      GRID_CHARGING_BULK: 27.9
      GRID_CHARGING_ESTIMATE: "pvEstimate"
      ACM_DEVICE: "/dev/ttyACM0"
      BMS_MODEL: "MUST"
      GRID_TIED: ""
      SOLCAST_ESTIMATE: "(pvEstimate+pvEstimate)/2"
      MAX_POWER_LIMIT: 5120
      TARGET_POWER: 4700 # 4760 resting at Float voltage 26.6, 4550 27.5, 4880 27.9
      LOW_POWER: 1500
      MIN_POWER: 1024
    depends_on:
      - influxdb
    tmpfs:
      - /var/run
  influxdb:
    # if you have non-arm-v7 architecture, use regular influxdb image
    image: arm32v7/influxdb
    restart: always
    ports:
      - "8086:8086" # expose for testing, no need in production
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: root
      DOCKER_INFLUXDB_INIT_PASSWORD: root
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
      DOCKER_INFLUXDB_INIT_RETENTION: 1095d
      INFLUXDB_DB: ups1
    volumes:
      - "metrics:/var/lib/influxdb"
  grafana:
    image: grafana/grafana:11.2.6 #latest
    restart: always
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
    depends_on:
      - influxdb
volumes:
  metrics:
  grafana-data: