{
 "title": "Home LiFePo12",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iPGrid" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Load",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Battery",
     "measurement": "inverter",
     "query": "SELECT -\"iBattPower\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT last(\"iBatteryVoltage\") FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT - last(\"iBattPower\") / last(\"iBatteryVoltage\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iSGrid" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Load",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iSLoad" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "measurement": "inverter",
     "query": "SELECT -\"iBattPower\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iSInverter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT last(\"pvVoltage\") FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT last(\"pvChargerPower\") / last(\"pvVoltage\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery",
     "measurement": "inverter",
     "query": "SELECT \"iBatteryVoltage\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "AC",
     "measurement": "inverter",
     "query": "SELECT \"bat_amps\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iRadiatorTemperature" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT \"bat_amps\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvRadiatorTemperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load",
     "measurement": "inverter",
     "query": "SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedLoadPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvAccumulatedPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Self",
     "measurement": "inverter",
     "query": "SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedSelfusePower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT \"ac\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "inverter",
     "query": "SELECT \"ac\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iGridVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}