{
 "title": "Accumulated",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Daily Max",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedLoadPower\")-min(\"iAccumulatedLoadPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "iPLoad::field", "operator": "<", "value": "6500" }
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedSelfusePower\")-min(\"iAccumulatedSelfusePower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "iPGrid" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Estimate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "fPVEstimate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load",
     "query": "SELECT max(\"iAccumulatedLoadPower\")-min(\"iAccumulatedLoadPower\") FROM \"inverter\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "PV",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Battery",
     "query": "SELECT max(\"iAccumulatedSelfusePower\")-min(\"iAccumulatedSelfusePower\") FROM \"inverter\" WHERE $timeFilter fill(null)"
    },
    {
     "alias": "Estimate",
     "query": "SELECT sum(\"fPVEstimate\")/60000 FROM \"inverter\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iAccumulatedLoadPower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iAccumulatedSelfusePower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvAccumulatedPower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedLoadPower\")-min(\"iAccumulatedLoadPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "iAccumulatedLoadPower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "pvAccumulatedPower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Estimate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT sum(\"fPVEstimate\")/60000 FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "fPVEstimate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedSelfusePower\")-min(\"iAccumulatedSelfusePower\") FROM \"inverter\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "iAccumulatedSelfusePower" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}