{
 "title": "Day AGM24",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Load",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "iPLoad::field", "operator": "<", "value": "6500" }
     ]
    },
    {
     "alias": "Grid",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iPGrid" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "measurement": "inverter",
     "query": "SELECT -\"iBattPower\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iPInverter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "iPInverter::field", "operator": "<", "value": "6500" }
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Battery",
     "measurement": "inverter",
     "query": "SELECT \"iBattPower\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Estimate",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "fPVEstimate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "bargauge",
   "description": "<table>\n<tr><td>26v</td><td>100%</td></tr>\n<tr><td>25v</td><td>80%</td></tr>\n<tr><td>24.1v</td><td>50%</td></tr>\n<tr><td>23.6v</td><td>30%</td></tr>\n<tr><td>23v</td><td>10%</td></tr>\n<tr><td>21v</td><td>0%</td></tr>\n</table>",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT last(\"iBatteryVoltage\") FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT last(\"iBatteryVoltage\") FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT min(\"iBattPower\") / min(\"iBatteryVoltage\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT max(\"iBattPower\") / max(\"iBatteryVoltage\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load",
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedLoadPower\") - min(\"iAccumulatedLoadPower\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedLoadPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT max(\"pvAccumulatedPower\") - min(\"pvAccumulatedPower\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvAccumulatedPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Self",
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedSelfusePower\") - min(\"iAccumulatedSelfusePower\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedSelfusePower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Discharge",
     "measurement": "inverter",
     "query": "SELECT max(\"iAccumulatedDischargerPower\") - min(\"iAccumulatedDischargerPower\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedSelfusePower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Estimate",
     "query": "SELECT sum(\"fPVEstimate\")/60000 FROM \"inverter\" WHERE $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "PV",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT \"pvVoltage\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT \"pvChargerPower\" / \"pvVoltage\" FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AC",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iRadiatorTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvRadiatorTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "rPi",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "rpiTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "description": "<table>\n<tr><td>26v</td><td>100%</td></tr>\n<tr><td>25v</td><td>80%</td></tr>\n<tr><td>24.1v</td><td>50%</td></tr>\n<tr><td>23.6v</td><td>30%</td></tr>\n<tr><td>23v</td><td>10%</td></tr>\n<tr><td>21v</td><td>0%</td></tr>\n</table>",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery",
     "measurement": "inverter",
     "query": "SELECT \"iBatteryVoltage\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Work State",
   "type": "state-timeline",
   "description": "PV States: </BR>\nStop </BR>\nSelftest </BR>\nWork Modes: </BR>\nMPPT-A = MPPT, Absorb charge </BR>\nMPPT-F = MPPT, Float charge </BR>\nCL-F = Current limiting, Float charge </BR>\nCL-A = Current limiting, Absorb charge </BR>",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "alias": "Inverter",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iWorkState" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Error",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iError" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Warning",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iWarning" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvWorkState" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV Error",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvError" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Warning",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvWarning" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Energy",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "icEnergyUse" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT \"ac\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}