{
 "title": "Home AGM24ax",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Load",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Grid",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iPGrid" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Inverter",
     "measurement": "inverter",
     "query": "SELECT -\"iBattPower\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iPInverter" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Battery",
     "measurement": "inverter",
     "query": "SELECT \"iBattPower\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Estimate",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "fPVEstimate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "description": "<table>\n<tr><td>26v</td><td>100%</td></tr>\n<tr><td>25v</td><td>80%</td></tr>\n<tr><td>24.1v</td><td>50%</td></tr>\n<tr><td>23.6v</td><td>30%</td></tr>\n<tr><td>23v</td><td>10%</td></tr>\n<tr><td>21v</td><td>0%</td></tr>\n</table>",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT last(\"iBatteryVoltage\") FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT last(\"iBattPower\") / last(\"iBatteryVoltage\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBattPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "AC",
     "measurement": "inverter",
     "query": "SELECT \"bat_amps\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iRadiatorTemperature" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT \"bat_amps\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvRadiatorTemperature" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "rPi",
     "measurement": "inverter",
     "query": "SELECT \"bat_amps\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "rpiTemperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT last(\"pvVoltage\") FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "inverter",
     "query": "SELECT last(\"pvChargerPower\") / last(\"pvVoltage\") FROM \"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvChargerPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "inverter",
     "query": "SELECT \"ac\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iGridVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "description": "<table>\n<tr><td>26v</td><td>100%</td></tr>\n<tr><td>25v</td><td>80%</td></tr>\n<tr><td>24.1v</td><td>50%</td></tr>\n<tr><td>23.6v</td><td>30%</td></tr>\n<tr><td>23v</td><td>10%</td></tr>\n<tr><td>21v</td><td>0%</td></tr>\n</table>",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Voltage",
     "measurement": "inverter",
     "query": "SELECT \"iBatteryVoltage\" FROM \"autogen\".\"inverter\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iBatteryVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Load",
     "measurement": "inverter",
     "query": "SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedLoadPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvAccumulatedPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Battery",
     "measurement": "inverter",
     "query": "SELECT non_negative_difference(\"discharge\") AS ph1 FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "iAccumulatedSelfusePower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Work State",
   "type": "state-timeline",
   "description": "PV States: </BR>\nStop </BR>\nSelftest </BR>\nWork Modes: </BR>\nMPPT-A = MPPT, Absorb charge </BR>\nMPPT-F = MPPT, Float charge </BR>\nCL-F = Current limiting, Float charge </BR>\nCL-A = Current limiting, Absorb charge </BR>",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "alias": "Inverter",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iWorkState" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Error",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iError" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Warning",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "iWarning" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvWorkState" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "PV Error",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvError" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Warning",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "pvWarning" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Energy",
     "measurement": "inverter",
     "select": [
      [
       { "params": [ "icEnergyUse" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "PV",
     "measurement": "inverter",
     "query": "SELECT \"ac\" FROM \"autogen\".\"logs\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvVoltage" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}