{
 "title": "solcast",
 "time": { "from": "now/d", "to": "now/d+2d" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Estimates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Pessimistic",
     "measurement": "solcast",
     "query": "SELECT \"pvEstimate10\" FROM \"solcast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvTime" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Realistic",
     "measurement": "solcast",
     "query": "SELECT \"pvEstimate\" FROM \"solcast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvTime" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Optimistic",
     "measurement": "solcast",
     "query": "SELECT \"pvEstimate90\" FROM \"solcast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvTime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated Total",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Pessimistic",
     "measurement": "solcast",
     "query": "SELECT Estimate from (select sum(\"pvEstimate10\")/2 as Estimate FROM \"solcast\" GROUP BY time(1d) tz('Europe/Kiev'))\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvTime" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Realistic",
     "measurement": "solcast",
     "query": "SELECT Estimate from (select sum(\"pvEstimate\")/2 as Estimate FROM \"solcast\" GROUP BY time(1d) tz('Europe/Kiev'))\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvEstimate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Optimistic",
     "measurement": "solcast",
     "query": "SELECT Estimate from (select sum(\"pvEstimate90\")/2 as Estimate FROM \"solcast\" GROUP BY time(1d) tz('Europe/Kiev'))\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "pvTime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Week Averages",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "inverter",
     "query": "SELECT mean(\"iPLoad\") FROM \"inverter\" WHERE time >= now() - 7d GROUP BY time(30m) tz('Europe/Kiev')",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Week History",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Load",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "inverter",
     "query": "SELECT sum(\"iPLoad\")/60 FROM \"inverter\" WHERE time >= now() - 7d GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PV",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "inverter",
     "query": "SELECT sum(\"pvChargerPower\")/60 FROM \"inverter\" WHERE time >= now() - 7d GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "iPLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "query": "SELECT sum(\"iPGrid\")/60 FROM \"inverter\" WHERE time >= now() - 7d GROUP BY time(1d)"
    }
   ]
  }
 ]
}